require_relative './config/environment'
require 'sinatra/activerecord/rake'

#description
desc "Runs a Pry console"
task :console do
  # This line turns on logging of the SQL generated by ActiveRecord
  ActiveRecord::Base.logger = Logger.new(STDOUT)
  
  # Open a Pry session
  Pry.start
end